site_name: TacLibrary
site_url: https://tac1402.github.io/TacBattleAI/

theme:
  name: material
  locale: ru

nav:
  - О библиотеке: index.md
  - Архитектура библиотеки: architecture.md
  - Архитектурная легкость: simplicity.md
  - Отделение логики: separation.md
  - Линковка с библиотекой: linking.md
  - Standart+Unity: StandartU.md
  - TacStandartU: 
    - Item: TacStandartU/Item.md
    - BuildItem: TacStandartU/BuildItem.md
    - EntityType: TacStandartU/EntityType.md
    - DayNight: TacStandartU/DayNight.md
    - IObject: TacStandartU/IObject.md
    - BoundsExt: TacStandartU/BoundsExt.md
  - TacStandart:
    - Component: TacStandart/Component.md
    - Vector: TacStandart/Vector.md
    - GameTime: TacStandart/GameTime.md
    - NamedValue: TacStandart/NamedValue.md
    - RandomWorld: TacStandart/RandomWorld.md
    - RandomUnique: TacStandart/RandomUnique.md
  - TacItemCreate:
    - ItemCreate: TacItemCreate/ItemCreate.md
    - GhostCache: TacItemCreate/GhostCache.md
  - TacCamera:
    - TopCamera: TacCamera/TopCamera.md
    - FastController: TacCamera/FastController.md
  - TacWireframe:
    - Wireframe: TacWireframe/Wireframe.md
  - TacItemMove:
    - TurnInfo: TacItemMove/TurnInfo.md
    - ItemTurn: TacItemMove/ItemTurn.md
    - TopCameraExt: TacItemMove/TopCamera_.md
    - ItemCollision: TacItemMove/ItemCollision.md
    - ItemBuild: TacItemMove/ItemBuild.md
  - TacAgent:
    - Agent: TacAgent/Agent.md
    - AgentLogic: TacAgent/AgentLogic.md
    - AgentAnimator: TacAgent/AgentAnimator.md
    - Eye: TacAgent/Eye.md
    - AgentInPoint: TacAgent/AgentInPoint.md
    - AgentPoint: TacAgent/AgentPoint.md
  - TacAgent UI:
    - AgentSelection: TacAgent/AgentSelection.md
    - HealthBar: TacAgent/HealthBar.md
    - StatusBar: TacAgent/StatusBar.md
  - TacHealth:
    - BodyParts: TacHealth/BodyParts.md
    - PhysicalSkill: TacHealth/PhysicalSkill.md
    - VitalSystems: TacHealth/VitalSystems.md
    - HealthState: TacHealth/HealthState.md
  - TacPerson:
    - PersonLogic: TacPerson/PersonLogic.md
    - Person: TacPerson/Person.md
    - PersonPlan: TacPerson/PersonPlan.md
    - PersonNameLogic: TacPerson/PersonNameLogic.md
    - PersonName: TacPerson/PersonName.md
  - TacUI:
    - UI прототипирование: TacUI/UI.md
    - InfoPanel: TacUI/InfoPanel.md
    - InfoPanelManager: TacUI/InfoPanelManager.md
    - TableUI: TacUI/TableUI.md
  - TacSave:
    - SaveCatalog: TacSave/SaveCatalog.md
    - IDayNight: TacSave/IDayNight.md
    - ISaveManager: TacSave/ISaveManager.md
    - SaveManager0: TacSave/SaveManager0.md
    - SaveManager: TacSave/SaveManager.md
    - ILoadManager: TacSave/ILoadManager.md
  - DirectConvert:
    - Сохранение игры: TacDConvert/DConvert.md
    - IPrefabId: TacDConvert/IPrefabId.md
    - IDataSave: TacDConvert/IDataSave.md
    - DataSave: TacDConvert/DataSave.md
