site_name: TacLibrary
site_url: https://tac1402.github.io/TacBattleAI/

theme:
  name: material
  locale: ru

nav:
  - О библиотеке: index.md
  - Архитектура библиотеки: architecture.md
  - Архитектурная легкость: simplicity.md
  - Отделение логики: separation.md
  - Линковка с библиотекой: linking.md
  - TacStandart: 
    - Item: TacStandart/Item.md
    - ModelTypes: TacStandart/ModelTypes.md
    - Component: TacStandart/Component.md
    - BuildItem: TacStandart/BuildItem.md
    - Vector: TacStandart/Vector.md
    - RandomWorld: TacStandart/RandomWorld.md
    - RandomUnique: TacStandart/RandomUnique.md
  - TacItemCreate:
    - ItemCreate: TacItemCreate/ItemCreate.md
    - EntityType: TacItemCreate/EntityType.md
    - GhostCache: TacItemCreate/GhostCache.md
  - TacCamera:
    - TopCamera: TacCamera/TopCamera.md
    - FastController: TacCamera/FastController.md
  - TacWireframe:
    - Wireframe: TacWireframe/Wireframe.md
  - TacItemMove:
    - TurnInfo: TacItemMove/TurnInfo.md
    - ItemTurn: TacItemMove/ItemTurn.md
    - TopCameraExt: TacItemMove/TopCamera_.md
    - ItemCollision: TacItemMove/ItemCollision.md
    - ItemBuild: TacItemMove/ItemBuild.md
  - TacAgent:
    - Agent: TacAgent/Agent.md
    - AgentLogic: TacAgent/AgentLogic.md
    - AgentAnimator: TacAgent/AgentAnimator.md
    - Eye: TacAgent/Eye.md
    - AgentInPoint: TacAgent/AgentInPoint.md
    - AgentPoint: TacAgent/AgentPoint.md
  - TacHealth:
    - BodyParts: TacHealth/BodyParts.md
    - PhysicalSkill: TacHealth/PhysicalSkill.md
    - VitalSystems: TacHealth/VitalSystems.md
    - HealthState: TacHealth/HealthState.md
  - TacPerson:
    - PersonLogic: TacPerson/PersonLogic.md
    - Person: TacPerson/Person.md
    - PersonPlan: TacPerson/PersonPlan.md
    - PersonNameLogic: TacPerson/PersonNameLogic.md
    - PersonName: TacPerson/PersonName.md
  - TacUI:
    - UI прототипирование: TacUI/UI.md
    - InfoPanel: TacUI/InfoPanel.md
    - InfoPanelManager: TacUI/InfoPanelManager.md
    - TableUI: TacUI/TableUI.md

