site_name: TacLibrary
site_url: https://tac1402.github.io/TacBattleAI/

theme:
  name: material
  locale: ru

nav:
  - О библиотеке: index.md
  - Архитектурная легкость: simplicity.md
  - Отделение логики: separation.md
  - TacStandart: 
    - Item: TacStandart/Item.md
    - ModelTypes: TacStandart/ModelTypes.md
    - Component: TacStandart/Component.md
    - Item2: TacStandart/Item2.md
    - Vector: TacStandart/Vector.md
  - TacItemCreate:
    - ItemCreate: TacItemCreate/ItemCreate.md
    - EntityType: TacItemCreate/EntityType.md
    - GhostCache: TacItemCreate/GhostCache.md
  - TacCamera:
    - TopCamera: TacCamera/TopCamera.md
    - FastController: TacCamera/FastController.md
  - TacWireframe:
    - Wireframe: TacWireframe/Wireframe.md
  - TacItemMove:
    - TurnInfo: TacItemMove/TurnInfo.md
    - ItemTurn: TacItemMove/ItemTurn.md
    - TopCameraExt: TacItemMove/TopCamera_.md
    - ItemCollision: TacItemMove/ItemCollision.md
    - ItemBuild: TacItemMove/ItemBuild.md
  - TacAgent:
    - Agent: TacAgent/Agent.md
    - AgentAnimator: TacAgent/AgentAnimator.md
    - Eye: TacAgent/Eye.md
  - TacPerson:
    - Person: TacPerson/Person.md
    - PersonName: TacPerson/PersonName.md
