site_name: TacLibrary
site_url: https://tac1402.github.io/TacBattleAI/

theme:
  name: readthedocs
  locale: ru

nav:
  - О библиотеке: index.md
  - Архитектурная легкость: simplicity.md
  - TacStandart: TacStandart.md
    - Item: TacStandart/Item.md
    - ModelTypes: TacStandart/ModelTypes.md

