site_name: MyDoc
site_url: https://tac1402.github.io/TacBattleAI/

theme:
  name: material

nav:
  - Main: index.md
  - Install: getting-started/installation.md
  - aaa: 
    - ccc: getting-started/basics.md
    - test: getting-started/advanced.md
  - API: api.md
  - FAQ: faq.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true