title: TacLibrary
description: Documentation of TacLibrary
remote_theme: just-the-docs

nav_enabled: true

url: https://tac1402.github.io

aux_links:
  Template Repository: https://github.com/tac1402/TacBattleAI